# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 290b5fdc4b97a7e0eb687cce07d7087c4058bb5b3df0784cba841d5ecf2eb6c996fa561522467ceaa2a0a7ff057371ceeb3153101c51c886d355a39d82ced13b

test:
  secret_key_base: 6e5a28a1f8146710bead1a554d20b76929630033c47e563a408b3948f1acea730a88dd525a274be6416bc0ea65f4df4ebd2a506bc6e8f830bf9f1af5884adea2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
